// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketing.Data;

#nullable disable

namespace Ticketing.Migrations
{
    [DbContext(typeof(TicketingDBContext))]
    [Migration("20251103181617_SeedTickets")]
    partial class SeedTickets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("TicketNumbers", "shared");

            modelBuilder.Entity("Ticketing.Models.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR shared.TicketNumbers");

                    b.Property<int>("TicketStatus")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b6a5f2c8-9e44-4c1b-8f0d-2f8f65a7a3c1"),
                            AssignedUserId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            CreatedAt = new DateTime(2025, 11, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Users cannot log in after latest update",
                            TicketNo = 0,
                            TicketStatus = 0,
                            Title = "Fix login issue",
                            UpdatedAt = new DateTime(2025, 11, 3, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d3e2c5f1-7c4b-4b8d-83e0-bb7d5cbb4f11"),
                            AssignedUserId = new Guid("9a1b2c3d-4e5f-6789-abcd-1234567890ef"),
                            CreatedAt = new DateTime(2025, 11, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Redesign profile page for better UX",
                            TicketNo = 0,
                            TicketStatus = 1,
                            Title = "Update user profile page",
                            UpdatedAt = new DateTime(2025, 11, 3, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f8c4d7a2-1b2c-4d3f-a5e6-9f0b4c1d2e3f"),
                            AssignedUserId = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            CreatedAt = new DateTime(2025, 11, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Payment failures reported on checkout",
                            TicketNo = 0,
                            TicketStatus = 2,
                            Title = "Fix payment gateway",
                            UpdatedAt = new DateTime(2025, 11, 3, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c9a1b2d3-4e5f-6789-abcd-0f1e2d3c4b5a"),
                            AssignedUserId = new Guid("6b29fc40-ca47-1067-b31d-00dd010662da"),
                            CreatedAt = new DateTime(2025, 11, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Schedule downtime for server upgrades",
                            TicketNo = 0,
                            TicketStatus = 2,
                            Title = "Server maintenance",
                            UpdatedAt = new DateTime(2025, 11, 3, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e1f2d3c4-5b6a-7c8d-9e0f-1a2b3c4d5e6f"),
                            CreatedAt = new DateTime(2025, 11, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Some users are not receiving emails",
                            TicketNo = 0,
                            TicketStatus = 0,
                            Title = "Email notification bug",
                            UpdatedAt = new DateTime(2025, 11, 3, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Ticketing.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            Email = "programer@asdf.com",
                            Name = "Paul Brennan"
                        },
                        new
                        {
                            Id = new Guid("9a1b2c3d-4e5f-6789-abcd-1234567890ef"),
                            Email = "captainamerica@asdf.com",
                            Name = "Steve Rogers"
                        },
                        new
                        {
                            Id = new Guid("3fa85f64-5717-4562-b3fc-2c963f66afa6"),
                            Email = "batman@asdf.com",
                            Name = "Bruce Wayne"
                        },
                        new
                        {
                            Id = new Guid("6b29fc40-ca47-1067-b31d-00dd010662da"),
                            Email = "scarletwitch@asdf.com",
                            Name = "Wanda Maximoff"
                        },
                        new
                        {
                            Id = new Guid("e02fd0e4-00fd-090a-ca30-0d00a0038ba0"),
                            Email = "cyclops@asdf.com",
                            Name = "Scott Summers"
                        });
                });

            modelBuilder.Entity("Ticketing.Models.Ticket", b =>
                {
                    b.HasOne("Ticketing.Models.User", "AssignedUser")
                        .WithMany("Tickets")
                        .HasForeignKey("AssignedUserId");

                    b.Navigation("AssignedUser");
                });

            modelBuilder.Entity("Ticketing.Models.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
